# -*- coding: utf-8 -*-
"""Statistics Advanced -1 Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btmkbFByFPN-cgpdYbe2dOKhCNOedtyY

# **Statistics Advanced - 1| Assignment**

**1. What is a random variable in probability theory?**

- Definition:

- A random variable is a numerical outcome of a random experiment. It assigns a real number to each possible outcome in a sample space of a probabilistic event.

- Formally:

- A random variable is a function that maps outcomes of a probability space to real numbers.

- Types of Random Variables:

 1. Discrete Random Variable:
Takes on countable values.

 - Example: 0, 1, 2, 3...

 - Usually defined in events like coin tosses, dice rolls, or number of customers.

 - Example: Tossing a coin 3 times
Let X = number of heads
Then X can be: 0, 1, 2, or 3 → discrete

 2. Continuous Random Variable:

 - Takes on uncountable infinite values, typically over an interval.

 - Example: Height, weight, time, temperature.

 - Example: Let Y = temperature in Pune at noon
Then Y can be 32.1°C, 32.15°C, 32.156°C... → continuous

- Probability Functions:

- Discrete:

 - Uses a Probability Mass Function (PMF)

 - PMF:
𝑃
(
𝑋
=
𝑥
)

 - Example:

 - Let X = result of a die roll
Then,

   P(X=1)=P(X=2)=⋯=P(X=6)=
   6/1
​
 - Continuous:

 - Uses a Probability Density Function (PDF)

 - PDF:
𝑓
(
𝑥
)
 such that

 - 𝑃
(
𝑎
<
𝑋
<
𝑏
)
=
∫
𝑎
𝑏
𝑓
(
𝑥
)
𝑑
𝑥

- Important Concepts:

- Expected Value (Mean):

 - 𝐸
[
𝑋
]
=
∑
𝑥
⋅
𝑃
(
𝑋
=
𝑥
)
(Discrete)

 - 𝐸
[
𝑋
]
=
∫
𝑥
⋅
𝑓
(
𝑥
)
𝑑
𝑥
(Continuous)

 - Variance:

 - Measures the spread of values around the mean.

- Conclusion:

 - A random variable is a fundamental concept in probability and statistics that links real-world uncertainty to mathematical models. It enables the use of formulas, graphs, and probabilities to predict and analyze outcomes.

**2. What are the types of random variables?**

- There are two main types of random variables:

1. Discrete Random Variable

 - Definition:

 - A discrete random variable takes on a finite or countably infinite set of distinct values.

 - It is used when the outcomes can be counted, even if they are infinite.

 - Example Values:
  
    0, 1, 2, 3, ...

 - Characteristics:

 - Countable values

 - Uses Probability Mass Function (PMF) to assign probabilities

 - Total probability:

 - ∑
𝑃
(
𝑋
=
𝑥
𝑖
)
=
1

- Example:

| Experiment              | Random Variable (X)                  |
| ----------------------- | ------------------------------------ |
| Tossing a coin 3 times  | Number of heads (0, 1, 2, 3)         |
| Rolling a die           | Result (1 to 6)                      |
| Surveying 10 people     | No. who say "Yes" (0 to 10)          |
| Number of cars per hour | 0, 1, 2, 3... (Poisson distribution) |

2. Continuous Random Variable

 -  Definition:

 - A continuous random variable can take any value within a given range or interval, including decimals.

 - It is used when the outcomes are measurable and uncountably infinite.

 - Characteristics:

 - Uncountable number of values

 - Uses a Probability Density Function (PDF)

 - Probability at exact value is 0:

 - 𝑃
(
𝑋
=
𝑎
)
=
0

 - Probability is defined over an interval:

 - 𝑃
(
𝑎
<
𝑋
<
𝑏
)
=
∫
𝑎
𝑏
𝑓
(
𝑥
)
𝑑
𝑥

- Example:

| Situation                    | Random Variable (X)           |
| ---------------------------- | ----------------------------- |
| Measuring height of students | Height in cm (e.g., 156.4 cm) |
| Time taken to run a race     | Seconds (e.g., 9.84 sec)      |
| Temperature in Pune          | 29.7°C, 30.0°C, etc.          |
| Voltage in a circuit         | 5.02V, 5.19V, etc.            |

- Conclusion:

 - Random variables are classified based on the nature of their possible values. Discrete variables deal with counting, while continuous variables deal with measuring. Understanding this difference is essential in probability theory, statistics, and real-world applications like machine learning, finance, and science.

**3. Explain the difference between discrete and continuous distributions.**

- Definition:

 - A probability distribution describes how the values of a random variable are spread out or distributed.

 - There are two main types of distributions, based on the type of random variable:

- 1. Discrete Probability Distribution

 - Definition:

 - A discrete distribution describes the probability of a discrete random variable, which takes countable values.

 - Example Values:

    0, 1, 2, 3, ...

 - Key Features:

 - Values are distinct and separate

 - Total probability adds up to 1

 - ∑
𝑃
(
𝑋
=
𝑥
𝑖
)
=
1
 - Represented using a Probability Mass Function (PMF)

- Examples of Discrete Distributions:

| Distribution           | Used When                                  |
| ---------------------- | ------------------------------------------ |
| Binomial Distribution  | Fixed number of trials (e.g. coin tosses)  |
| Poisson Distribution   | Events per time unit (e.g. calls per hour) |
| Geometric Distribution | First success after x failures             |

 - Graphical Representation:

 - Bar chart (non-connected)

 - Each bar shows the probability of a value

2. Continuous Probability Distribution

 - Definition:

 - A continuous distribution describes the probability of a continuous random variable, which can take infinite values within a range.

 - Example Values:

    2.31, 5.87, 100.0001, etc.

 - Key Features:

 - Values form a continuum (no gaps)

 - Probability of an exact value is zero:

 - 𝑃
(
𝑋
=
𝑎
)
=
0

 - Uses a Probability Density Function (PDF)

 - Probability over interval:

 - 𝑃
(
𝑎
<
𝑋
<
𝑏
)
=
∫
𝑎
𝑏
𝑓
(
𝑥
)
𝑑
𝑥

- Examples of Continuous Distributions:

| Distribution             | Used When                                   |
| ------------------------ | ------------------------------------------- |
| Normal Distribution      | Natural/biological measurements (height)    |
| Uniform Distribution     | Equal chance in a range                     |
| Exponential Distribution | Time until event (e.g., light bulb failure) |

 - Graphical Representation:

 - Smooth curve

 -  Area under curve represents probability

- Comparison Table:

| Feature                    | Discrete Distribution           | Continuous Distribution            |
| -------------------------- | ------------------------------- | ---------------------------------- |
| Type of Variable           | Discrete (countable)            | Continuous (infinite values)       |
| Values                     | 0, 1, 2, 3, ...                 | 1.5, 3.42, 100.01, ...             |
| Function Used              | PMF (Probability Mass Function) | PDF (Probability Density Function) |
| Probability of exact value | > 0                             | Always 0                           |
| Graph                      | Bar graph                       | Curve (area = probability)         |

- Example:

 - Discrete Case:
Roll a die
P(X = 3) = 1/6

 - Continuous Case:
Measure rainfall in cm
P(X = 2.5 cm) = 0
P(2.4 cm < X < 2.6 cm) = Area under curve

- Conclusion:

 - The key difference lies in the type of values the variable can take. Discrete distributions handle counted values with PMFs, while continuous distributions handle measured values using PDFs. Understanding both is essential in data science, risk modeling, and analytics.

**4. What is a binomial distribution, and how is it used in probability?**

- Definition:

 - A binomial distribution is a discrete probability distribution that models the number of successes in a fixed number of independent Bernoulli trials (i.e., trials with only two outcomes: success or failure), where the probability of success remains constant.

- Formula (Probability Mass Function):

 - 𝑃
(
𝑋
=
𝑘
)
=
(
𝑛
𝑘
)
⋅
𝑝
𝑘
⋅
(
1
−
𝑝
)
𝑛
−
𝑘

- Where:

 - X = number of successes

 - n = total number of trials

 - k = number of successes

 - p = probability of success in one trial

 - (
𝑛
𝑘
)
(
k
n
​
 ) = combinations =
𝑛
!
𝑘
!

- Conditions (When to Use It):

 - A binomial distribution is used when:

 - There are n independent trials

 - Each trial has only 2 outcomes: Success or Failure

 - The probability of success p is constant across trials

 - You are interested in the number of successes (not the order)

- Real-Life Examples:

| Scenario                 | Success       | Failure   | n  | p    |
| ------------------------ | ------------- | --------- | -- | ---- |
| Tossing a coin 5 times   | Heads         | Tails     | 5  | 0.5  |
| Quality check in factory | Non-defective | Defective | 20 | 0.95 |
| Correct answers in quiz  | Correct       | Wrong     | 10 | 0.6  |

- 📊 Example Calculation:

 - Q. What is the probability of getting exactly 3 heads in 5 coin tosses?

 - 𝑛
=
5
𝑘
=
3
𝑝 = 0.5

 - 𝑃 ( 𝑋 = 3 ) = ( 5/3 ) ⋅ (0.5 )
 3.( 0.5 ) 2 = 10 ⋅ 0.125 ⋅ 0.25 = 0.3125

- Use Cases in Probability:

| Field           | Use Case                            |
| --------------- | ----------------------------------- |
| Statistics      | Estimating population proportions   |
| Quality Control | Checking defective items in samples |
| Medicine        | Success rate of treatments          |
| Business        | Probability of customer conversions |

- Visual Representation:

 - The distribution is usually bell-shaped when
    𝑝 = 0.5 and n is large

 - It becomes skewed if
    𝑝 is far from 0.5

- Conclusion:

 - The binomial distribution is a powerful and commonly used tool in probability theory for modeling binary (yes/no) events over repeated trials. It helps predict outcomes, understand uncertainty, and make informed decisions in data analysis and real-world scenarios.

**5. What is the standard normal distribution, and why is it important?**

- Definition:

 - The standard normal distribution is a special case of the normal distribution with:

 - Mean (μ) = 0

 - Standard deviation (σ) = 1

 - It is a bell-shaped, symmetric probability distribution that plays a central role in statistics and probability theory.

- Probability Density Function (PDF):

 - 𝑓
(
𝑧
)
=
1
2
𝜋
𝑒
−
𝑧
2
2
f(z)=
2π
1
 e
−
2
z
2

- Where:

 - 𝑧
    z = standardized value

 - 𝑒
    e ≈ 2.718

 - 𝜋
    π ≈ 3.1416

- Z-score (Standardization):

 - Any normal variable

 - 𝑋
∼
𝑁
(
𝜇
,
𝜎
2
)
X∼N(μ,σ
2
 ) can be converted to a standard normal variable
𝑍
Z using:
𝑍
=
𝑋
−
𝜇
𝜎
Z=
σ
X−μ
​

 - This process is called standardization, and it allows us to use the standard normal table (Z-table) for probability calculations.

- 📊 Why Is It Important?

 1. Universal Benchmark:

 - It allows us to compare scores from different normal distributions by converting to a common scale.

 2. Used in Hypothesis Testing:

 - Z-scores and standard normal distribution help in:

 - Confidence intervals

 - Z-tests

 - Significance testing (p-values)

 3. Simplifies Probability Calculation:

 - Instead of complex integration, we use Z-tables to find probabilities quickly.

 4. Basis of Many Other Distributions:

 - The central limit theorem states that the sampling distribution of the sample mean approaches a normal distribution — making the standard normal crucial in inferential statistics.

 5. Machine Learning & AI:

 - Data preprocessing (feature scaling/normalization)

 - Gaussian Naive Bayes classifier

 - Anomaly detection

**6. What is the Central Limit Theorem (CLT), and why is it critical in statistics?**

- Definition:

- The Central Limit Theorem (CLT) states that:

 - When independent random variables are added, their normalized sum tends toward a normal distribution—even if the original variables themselves are not normally distributed—provided the sample size is sufficiently large.

- Mathematically:

- Let:

 - 𝑋
1
,
𝑋
2
,
.
.
.
,
𝑋
𝑛
X
1
​
 ,X
2
​
 ,...,X
n
​
  be a random sample from any population (with mean
𝜇
μ and standard deviation
𝜎
σ)

 - Then the sampling distribution of the sample mean

 - 𝑋
ˉ
X
ˉ
  approaches a normal distribution as
𝑛
→
∞
n→∞
𝑋
ˉ
∼
𝑁
(
𝜇
,
𝜎
2
𝑛
)
X
ˉ
 ∼N(μ,
n
σ
2
 )

- Visual Explanation:

 - Even if your original population is:

 - Skewed

 - Uniform

 - Bimodal

 - The distribution of the sample mean will still tend to become normal with increasing sample size.

- Example:

 - Suppose the weights of mangoes in a village are skewed (non-normal), with:

 - Mean
𝜇
=
500
μ=500g

 - Standard deviation
𝜎
=
100
σ=100g

 - You take repeated samples of size
𝑛
=
40
n=40 and compute their means.

- According to CLT:

 - The distribution of sample means
𝑋
ˉ
X
ˉ
  becomes approximately normal:

 - 𝑋
ˉ
∼
𝑁
(
500,
100
2
40
)
=
𝑁
(
500,
15.81
)
Xˉ
∼N
(500,
40
100
2
 )=N(500,15.81)

- Why is CLT Critical in Statistics?

| Reason                                 | Explanation                                                             |
| -------------------------------------- | ----------------------------------------------------------------------- |
| Foundation for Hypothesis Testing    | Allows use of Z-test and t-test even when population is unknown         |
| Enables Confidence Intervals         | For estimating population parameters using sample statistics            |
| Supports Inferential Statistics      | Draw conclusions about population from sample data                      |
| Validates Use of Normal Distribution | Many parametric tests assume normality—CLT justifies it                 |
| Useful in Big Data & AI              | Aggregates and averages tend to normal, helping models work efficiently |

- Conclusion:

 - The Central Limit Theorem is one of the most powerful and fundamental concepts in statistics. It allows analysts to use the normal distribution as an approximation for many real-world problems—even when data isn't normal. This opens the door to a wide range of analytical tools, from confidence intervals to hypothesis tests.

**7. What is the significance of confidence intervals in statistical analysis?**

- Definition:

 - A confidence interval (CI) is a range of values, derived from sample data, that is likely to contain the true population parameter (like the mean or proportion) with a certain level of confidence.

 - For example, a 95% confidence interval for the mean might be:

 - CI=[48.3,52.7]

 - Which means: "We are 95% confident that the true population mean lies between 48.3 and 52.7."

- 📌 Why Confidence Intervals Are Important:

| Importance                        | Description                                                                              |
| --------------------------------- | ---------------------------------------------------------------------------------------- |
|  Reflects **uncertainty**        | Unlike point estimates, CI gives a **range** to express uncertainty in sample statistics |
|  Enables **inference**           | Helps estimate **unknown population parameters** based on sample data                    |
|  Aids **decision making**        | Businesses, scientists, and policymakers use CIs to assess **risk and reliability**      |
|  Avoids **false certainty**      | Provides a balanced view instead of misleading single-value estimates                    |
|  Supports **hypothesis testing** | CI that excludes a value (like 0) can be used to **reject null hypothesis**              |

- Mathematical Formula:

 - For the sample mean:

 - CI
=
𝑥
ˉ
±
𝑧
∗
⋅
𝑠
𝑛
CI=
x
ˉ
 ±z
∗
 ⋅
n
s
Where:
𝑥
ˉ
x
ˉ
  = sample mean
𝑧
∗
z
∗
  = Z-value for desired confidence level (e.g. 1.96 for 95%)
𝑠
s = sample standard deviation
𝑛
n = sample size

- Example:

 - You measure the heights of 100 students, getting:

 - Sample mean
 - 𝑥
ˉ
=
170
x
ˉ
 =170 cm

 - Standard deviation
 - 𝑠
=
10
s=10 cm

 - Sample size
 - 𝑛
=
100
n=100

 - Confidence level = 95% (Z = 1.96)

 - CI=170±1.96⋅
100
10
 =170±1.96
⇒
[
168.04
,
171.96
]
[168.04,171.96]

 - So you can say: "We are 95% confident that the true mean height of the student population is between 168.04 cm and 171.96 cm."

- Conclusion:

 - Confidence intervals are a fundamental concept in inferential statistics. They allow researchers to estimate population parameters in a realistic and transparent way. By providing a range rather than a single value, they account for sampling variability and enhance the reliability of conclusions in data-driven decision-making.

**8. What is the concept of expected value in a probability distribution?**

- Definition:

 - The expected value (EV) of a random variable is the long-run average outcome of a random process if it were repeated many times.
 It represents the "center" or "mean" of a probability distribution.

 - It is often denoted by:

 - 𝐸
[
𝑋
]
E[X]
𝜇
μ (mu)

- Intuition:

 - Think of expected value as:

 - “What do you expect on average if you repeat a random experiment infinitely many times?”

 - It is a weighted average of all possible values, where the weights are the probabilities.

- Formulas:

 - For a Discrete Random Variable:

 - 𝐸
[
𝑋
]
=
∑
𝑖
𝑥
𝑖
⋅
𝑃
(
𝑥
𝑖
)
E[X]=
i
∑
​
 x
i
​
 ⋅P(x
i
​
 )

 - Where:
 - 𝑥
𝑖
x
i
​
 : possible value of the random variable

 - 𝑃
(
𝑥
𝑖
)
P(x
i
 ): probability of that value

- For a Continuous Random Variable:
 - E[X]=∫
−∞
∞
 x⋅f(x)dx

- Where:

 - 𝑓
(
𝑥
)
f(x): probability density function (PDF)

- Example 1 (Discrete):

 - Suppose you roll a fair 6-sided die. The possible values are 1 through 6.

 - 𝐸
[
𝑋
]
=
∑
𝑖
=
1
6
𝑥
𝑖
⋅
𝑃
(
𝑥
𝑖
)=1+2+3+4+5+66=3.5E[X]=
i=1
∑
6
 x
i
 ⋅P(x
i
 )=
6
1+2+3+4+5+6
 =3.5

 - So, even though you never roll a "3.5", the average outcome over many rolls is 3.5.

 - Example 2 (Real-Life - Lottery):

 - Imagine a game where:

 - Win ₹500 with probability 0.1

 - Win ₹0 with probability 0.9

 - 𝐸
[
𝑋
]=500⋅0.1+0⋅0.9=50E[X]=500⋅0.1+0⋅0.9=50
→ On average, you earn ₹50 per game (even though most people win ₹0).
This helps evaluate fairness or profitability of a game.

-  Why Expected Value Matters:

| Reason                          | Importance                                |
| ------------------------------- | ----------------------------------------- |
|  Central Tendency              | Shows where values tend to cluster        |
|  Decision Making               | Used in economics, finance, risk analysis |
|  Forecasting                   | Helps predict future averages             |
|  Optimization                  | Basis for strategies in AI/game theory    |
|  Insurance & Actuarial Science | Premiums calculated using EV of claims    |

- Conclusion:

 - The expected value is a core concept in probability theory, reflecting the average or mean result of a random experiment. It’s widely used in statistics, economics, finance, machine learning, and daily life to support rational decision-making under uncertainty.

**9. Write a Python program to generate 1000 random numbers from a normal
distribution with mean = 50 and standard deviation = 5. Compute its mean and standard
deviation using NumPy, and draw a histogram to visualize the distribution.**

- Here is a complete Python program that:

 - Generates 1000 random numbers from a normal distribution with
mean = 50 and standard deviation = 5

 - Computes the sample mean and standard deviation using NumPy

 - Draws a histogram to visualize the distribution using matplotlib

- What We’ll See:

 - A bell-shaped histogram centered around 50

 - Red dashed line showing the sample mean

 - Approximate spread of data from 45 to 55 (due to std = 5)

- Python Program:
"""

import numpy as np
import matplotlib.pyplot as plt

# Step 1: Generate 1000 random numbers from normal distribution
mean = 50
std_dev = 5
data = np.random.normal(loc=mean, scale=std_dev, size=1000)

# Step 2: Compute mean and standard deviation using NumPy
computed_mean = np.mean(data)
computed_std = np.std(data)

print(f"Computed Mean: {computed_mean:.2f}")
print(f"Computed Standard Deviation: {computed_std:.2f}")

# Step 3: Plot histogram
plt.figure(figsize=(8, 5))
plt.hist(data, bins=30, color='skyblue', edgecolor='black')
plt.axvline(computed_mean, color='red', linestyle='dashed', linewidth=2, label=f'Mean = {computed_mean:.2f}')
plt.title('Histogram of Normally Distributed Data')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.legend()
plt.grid(True)
plt.show()

"""**10. You are working as a data analyst for a retail company. The company has
collected daily sales data for 2 years and wants you to identify the overall sales trend.
daily_sales = [220, 245, 210, 265, 230, 250, 260, 275, 240, 255,
235, 260, 245, 250, 225, 270, 265, 255, 250, 260]
● Explain how you would apply the Central Limit Theorem to estimate the average sales
with a 95% confidence interval.
● Write the Python code to compute the mean sales and its confidence interval.**

- Part 1: Explanation (Theory)

 - You are given a sample of daily sales values, and you want to estimate the average sales for the entire population of daily sales over 2 years.

 - Since we don't have the full population, we use the Central Limit Theorem (CLT):

 - CLT says that the distribution of the sample mean will approach a normal distribution, even if the data isn't normally distributed, as long as the sample size is large (usually
𝑛
≥
30
n≥30) or the population is normal.

 - In our case:

 - Sample size = 20 (slightly below 30, but we’ll proceed assuming approximate normality)

 - We estimate the population mean using:

 - Confidence Interval (CI)=
𝑥
ˉ
±
𝑧
⋅
𝑠
𝑛
 - Confidence Interval (CI)=
x
ˉ
 ±z⋅
n
​
s
​

- Where:

 - 𝑥
ˉ
x
ˉ
 : sample mean

 - 𝑠
s: sample standard deviation

 - 𝑛
n: sample size

 - 𝑧
z: Z-score for 95% CI = 1.96

- Conclusion:

 - With 95% confidence, we estimate that the true average daily sales over the 2 years lies between ₹241.86 and ₹254.14. This interval gives the company a range to plan inventory, forecast revenue, or assess growth.

- Part 2: Python Code to Compute Mean & 95% Confidence Interval
"""

import numpy as np
import scipy.stats as stats

# Daily sales data
daily_sales = [220, 245, 210, 265, 230, 250, 260, 275, 240, 255,
               235, 260, 245, 250, 225, 270, 265, 255, 250, 260]

# Step 1: Calculate sample mean and standard deviation
mean_sales = np.mean(daily_sales)
std_sales = np.std(daily_sales, ddof=1)  # sample standard deviation
n = len(daily_sales)

# Step 2: Calculate 95% Confidence Interval using CLT
z = 1.96  # Z-score for 95% confidence
margin_of_error = z * (std_sales / np.sqrt(n))

lower_bound = mean_sales - margin_of_error
upper_bound = mean_sales + margin_of_error

# Step 3: Display result
print(f"Mean Sales: {mean_sales:.2f}")
print(f"95% Confidence Interval: ({lower_bound:.2f}, {upper_bound:.2f})")